### ISSUE TITLE
Filename build

### ISSUE THREAD

**Issue by petk** [julien-lang/atom-shebang-set-grammar#4]
When using filename `build` and it is set with either `#!/bin/bash` or `#!/bin/sh` shebang, somehow the syntax highlighting for shell script doesn't get applied.

Atom recognizes it as Nant Build file though.

**Comment by julien-lang** [comment]
Is the "Change grammar for non "plain text" files" setting checkbox checked or unchecked?

**Comment by petk** [comment]
Ah, yes. Got it, I've completely missed this option. Thanks. If I set it to plain texts also, that works. I guess build is specific name for Nant files after all.

I'll close this one since probably that's the correct behavior.

**Comment by IRobL** [comment]
Great work on this @julien-lang!  I got stumped with this for the first.  Being in a hurry trying to finish something, I glanced at the config settings and nothing jumped out.  

It might be handy to rename the entry with something like `Enable for non "plain text"`.  Even in a hurry, the word enable would likely catch the eye of someone shopping for a package to auto-highlight a file that 'for some reason' just won't highlight.

**Comment by julien-lang** [comment]
Hi @IRobL, thanks for the feedback. I got the same feeling crossing my mind when @petk reported this: I should rename this setting title.

Your suggestion is to replace `Change grammar for non "plain text" files` by `Enable for non "plain text"`. That makes sense for me since the "Change grammar" part is the whole point of the module itself. So it does not have to be reminded on each setting.

@petk what you think? Do you agree on this one or do you have another suggestion?

Also, it would be nice to review the setting description in the same time. Do you have any suggestion to improve it @IRobL ?

**Comment by petk** [comment]
I think that current label is ok and descriptive enough. But probably more useful would be to have a more detailed description:
```
the default behavior is to detect...
```
with the info on what non "plain text" files are. Difficult to say. At the same time current definition is also ok once you understand how it works I think.

**Comment by IRobL** [comment]
So is that setting enabling syntax detection for files that are already identified by their file name or extension?  If that's the case, I would write it something like this.  

`Override grammar for files identified by extension/ filename`
Files such as `Makefile` or `build` will automatically have syntax highlighting applied based on their filename.  Enable this option to override this syntax highlighting and use the sytanx detected from the shebang.

Also, I would set the order of this entry to 1, and the  second entry to 2.  That will make it look less like the checkbox is a part of the text entry input.

**Comment by petk** [comment]
That would work perfect. Thanks for all this effort on improving.

**Comment by julien-lang** [comment]
Ok guys, sorry for the delay. I pushed a branch with the code change.<
Sorry I can not check the "checkbox" thing without changing the setting type. It's a Boolean now and the only way to do what you describe @IRobL would be to switch to a Enum. But I don't really want that.

Anyway, if no comment are raised, I will merge that soon and publish a new version of the module.

**Comment by julien-lang** [comment]
I published a new version with this change.
